dbt_cloudrun_project:
  outputs:
    dev:
      dataset: sales_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: 'C:\Users\kirti\Downloads\key.json'
      location: US
      method: service-account
      priority: interactive
      project: airy-actor-457907-a8
      threads: 1
      type: bigquery
  target: dev

